# Generated by Django 6.0.3 on 2026-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="form.name.help", max_length=100, verbose_name="form.name.label")),
                (
                    "email",
                    models.EmailField(help_text="form.email.help", max_length=254, verbose_name="form.email.label"),
                ),
                ("message", models.TextField(help_text="form.message.help", verbose_name="form.message.label")),
            ],
            options={
                "verbose_name": "form.feedback.verbose_name",
                "verbose_name_plural": "form.feedback.verbose_name_plural",
            },
        ),
    ]
