# Generated by Django 5.2.11 on 2026-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live_translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationentry",
            name="context",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Optional gettext context (msgctxt). Used to disambiguate identical message IDs with different meanings. Leave blank for standard translations.",
                max_length=255,
                verbose_name="Context",
            ),
        ),
        migrations.AlterField(
            model_name="translationentry",
            name="language",
            field=models.CharField(
                db_index=True,
                help_text="Language code this translation applies to (e.g. cs, en, de, pl).",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="translationentry",
            name="msgid",
            field=models.TextField(
                help_text="The original translation key as it appears in the source code (e.g. 'hero-title').",
                verbose_name="Message ID",
            ),
        ),
        migrations.AlterField(
            model_name="translationentry",
            name="msgstr",
            field=models.TextField(
                blank=True,
                help_text="The translated text that overrides the .po file default. If set to the same value as the .po default, this record will be removed automatically.",
                verbose_name="Translation",
            ),
        ),
    ]
