# Generated by Django 6.0.3 on 2026-03-11 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live_translations", "0003_translationentry_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(db_index=True, max_length=10)),
                ("msgid", models.TextField()),
                ("context", models.CharField(blank=True, default="", max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("activate", "Activated"),
                            ("deactivate", "Deactivated"),
                        ],
                        max_length=10,
                    ),
                ),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation history entry",
                "verbose_name_plural": "Translation history entries",
                "db_table": "live_translations_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["msgid", "context", "language", "-created_at"],
                        name="lt_history_lookup",
                    )
                ],
            },
        ),
    ]
